### ISSUE TITLE
Dev server demo not working on mobile

### ISSUE THREAD

**Issue by cramrov** [runisland/meteor-ionic4#5]
Hi,

I'm running the Blaze demo on localhost, and when I open Safari or Chrome on my iOS or Android device pointing to the localhost IP of my LAN, I see a blank page. The demo runs OK on desktop.

Whats wrong?

Thank you!
/marc

**Comment by ghybs** [comment]
Hi,

Does the online demo work on your iOS and/or Android devices?
https://runisland.github.io/meteor-ionic4/blaze-flowrouter/
(I have not updated it in a while, but it should already give some idea)

Does a normal Meteor+Blaze (without Ionic4) project work fine when you access it from your mobile devices?

**Comment by ghybs** [comment]
FYI, I updated the online demos to version `4.0.0-beta.3`

**Comment by cramrov** [comment]
Hi @ghybs,
The online demo works well on mobile, and any other Meteor+Blaze (without ionic4) works well either. I've followed the insructions here in order to reproduce the demo locally: https://github.com/runisland/meteor-ionic4/tree/master/examples/blaze-flowrouter

Finally, I've updated the ionic4 package and still not working.

Thank you for helping me.

Regards,
/marc

**Comment by ghybs** [comment]
Hi,

Ok I see what is happening.

Ionic4 assets are retrieved using [`Meteor.absoluteUrl`](https://docs.meteor.com/api/core.html#Meteor-absoluteUrl), so that they are not affected by subpaths or prefix.

However, during development, Meteor sets [`ROOT_URL`](https://docs.meteor.com/environment-variables.html#ROOT-URL) by default to `http://localhost:3000`.
But when you try accessing your development server from another machine (typically from a mobile device), you connect to that localhost server typing the IP of your dev machine (e.g. `http://192.168.1.10:3000`), instead of `http://localhost:3000`.
Therefore `Meteor.absoluteUrl` now gives an URL that cannot be accessed by the remote machine.
So Ionic4 assets cannot be loaded in the device browser, and the app screen remains blank.

I think there are 2 good news then:
- This situation is only problematic during development, when `ROOT_URL` might be different from how you actually connect to the Meteor dev server. There should be no issue at all after build and deployment.
- The very easy workaround is to explicitly specify `ROOT_URL` environment variable even during development, if you want to be able to test it on another machine that cannot access `localhost`. For example on Linux and macOS:
```bash
$ ROOT_URL="http://<ip-address>:<port>" meteor run
```

**Comment by cramrov** [comment]
@ghybs , thank you for the discovery, the workaround works fine, I close the issue.
